#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
checks=[
('identity', 'SKILL.md', 'global-creative-product-intelligence-r9'),
('single front', 'SKILL.md', 'SINGLE FRONT DOOR'),
('dedupe', 'SKILL.md', 'ENTITY RESOLUTION / UPDATE-IN-PLACE'),
('director', 'SKILL.md', 'DIRECTOR BRAIN'),
('russian', 'SKILL.md', 'RUSSIAN OWNER/CUSTOMER GATE'),
('commands', 'SKILL.md', 'PROACTIVE QUICK COMMANDS'),
('product value', 'SKILL.md', 'PRODUCT VALUE INTEGRITY'),
('future self', 'SKILL.md', 'FOUNDER DEVELOPMENT / FUTURE SELF'),
('portfolio', 'SKILL.md', 'LIVE PORTFOLIO / PROOF-BEFORE-TEACH'),
('knowledge', 'SKILL.md', 'KNOWLEDGE CAPITAL MINING'),
('platform', 'SKILL.md', 'PLATFORM INTELLIGENCE'),
('owner no invention', 'SKILL.md', 'OWNER CONTEXT / NO-INVENTION'),
('workspace', 'SKILL.md', 'OWNER WORKSPACE ARCHITECT'),
('capability', 'SKILL.md', 'CAPABILITY EXPANSION RADAR'),
('model economics', 'SKILL.md', 'MODEL/REASONING ECONOMICS BY EVIDENCE'),
('architecture missing', 'SKILL.md', 'ARCHITECTURE COMPLETENESS / WHAT IS MISSING'),
('whitespace', 'SKILL.md', 'MARKET WHITESPACE / DO-NOT-GO'),
('restore ask', 'references/owner-context-diagnostic.md', 'Restore before ask'),
('materiality', 'references/owner-context-diagnostic.md', 'Materiality test'),
('diagnostic', 'references/owner-context-diagnostic.md', 'Diagnostic interview'),
('no fake profile', 'references/owner-context-diagnostic.md', 'No-invention gate'),
('profile writeback', 'references/owner-context-diagnostic.md', 'Personal profile write-back'),
('audience evidence', 'references/owner-context-diagnostic.md', 'Target audience is also evidence'),
('friction', 'references/owner-workspace-architecture.md', 'Workspace friction scan'),
('derived', 'references/owner-workspace-architecture.md', 'Derived-view rule'),
('exec cockpit', 'references/owner-workspace-architecture.md', 'Executive Cockpit'),
('content cockpit', 'references/owner-workspace-architecture.md', 'Content Cockpit'),
('commercial map', 'references/owner-workspace-architecture.md', 'Commercial Architecture Map'),
('audience map', 'references/owner-workspace-architecture.md', 'Audience & Demand Map'),
('product portfolio', 'references/owner-workspace-architecture.md', 'Product Portfolio'),
('knowledge library', 'references/owner-workspace-architecture.md', 'Knowledge Capital Library'),
('case gallery', 'references/owner-workspace-architecture.md', 'Portfolio / Case Gallery'),
('learning cockpit', 'references/owner-workspace-architecture.md', 'Founder Learning Cockpit'),
('dashboard criteria', 'references/owner-workspace-architecture.md', 'When to recommend a dashboard'),
('visual first', 'references/owner-workspace-architecture.md', 'Visual-first preference'),
('gap scan', 'references/owner-workspace-architecture.md', 'Proactive architecture gap scan'),
('client reuse', 'references/owner-workspace-architecture.md', 'Client-reusable architecture'),
('demo business', 'references/owner-workspace-architecture.md', 'Demo-business route'),
('cap gap', 'references/capability-expansion-radar.md', 'Capability-gap first'),
('cap search', 'references/capability-expansion-radar.md', 'Search order'),
('cap registry', 'references/capability-expansion-radar.md', 'Capability registry'),
('install gate', 'references/capability-expansion-radar.md', 'Install/recommend gate'),
('current only', 'references/capability-expansion-radar.md', 'Current information only'),
('model router', 'references/capability-expansion-radar.md', 'Model & reasoning router'),
('benchmark', 'references/capability-expansion-radar.md', 'Small benchmark before adoption'),
('opportunity scout', 'references/capability-expansion-radar.md', 'Opportunity scout'),
('not noisy', 'references/capability-expansion-radar.md', 'Proactive but not noisy'),
('model card', 'references/model-economics-routing.md', 'Per-task model decision card'),
('cheap proven', 'references/model-economics-routing.md', 'самый дешёвый ранее доказанный'),
('reasoning not default', 'references/model-economics-routing.md', 'максимальный reasoning не default'),
('deterministic media', 'references/model-economics-routing.md', 'media render/transcode'),
('context cost', 'references/model-economics-routing.md', 'большой контекст сначала индексируй'),
('model benchmark', 'references/model-economics-routing.md', 'representative benchmark'),
('executor history', 'references/tool-router.md', 'Executor reliability is a hard routing input'),
('owner context route', 'references/tool-router.md', 'Owner-context and workspace route'),
('cap route', 'references/tool-router.md', 'Capability expansion route'),
('not all video codex', 'references/tool-router.md', 'Do not route all video to Codex'),
('creative routing', 'references/tool-router.md', 'Creative / media route'),
('market do not go', 'references/strategy-portfolio.md', 'Market whitespace / do-not-go challenge'),
('whitespace research', 'references/research-competitive-intelligence.md', 'Whitespace research'),
('low comp demand', 'references/research-competitive-intelligence.md', 'малоконкурентно` не равно `есть спрос'),
('future card', 'references/founder-future-self-lab.md', 'Future-Self Card'),
('speech', 'references/founder-future-self-lab.md', 'Speaking & presence academy'),
('calendar', 'references/founder-future-self-lab.md', 'Identity-to-calendar rule'),
('no magic', 'references/founder-future-self-lab.md', 'Нельзя утверждать, что визуализация сама меняет внешнюю реальность'),
('portfolio gate', 'references/live-portfolio-proof.md', 'Portfolio-grade gate'),
('proof teach', 'references/live-portfolio-proof.md', 'Proof-before-teach'),
('work asset', 'references/knowledge-capital-product-mining.md', 'Work-to-asset scan'),
('capital dedupe', 'references/knowledge-capital-product-mining.md', 'Dedupe-first capitalization'),
('capital card', 'references/knowledge-capital-product-mining.md', 'Capitalization Card'),
('platform card', 'references/platform-intelligence-operations.md', 'Platform card'),
('algorithm truth', 'references/platform-intelligence-operations.md', 'Algorithm truth hierarchy'),
('channel hub', 'references/platform-intelligence-operations.md', 'Channel data hub'),
('creative rescue', 'references/creative-content-production.md', 'Weak-Idea Rescue Ladder'),
('creative challenge', 'references/creative-content-production.md', 'Creative route challenge'),
('shoot card', 'references/creative-content-production.md', 'Founder on-camera direction'),
('first pass', 'references/creative-content-production.md', 'First-pass is not handoff'),
('video producer', 'references/media-production-quality.md', 'Producer / story / pacing'),
('video critique', 'references/media-production-quality.md', 'First cut → critique → final export'),
('product semantic', 'references/product-value-integrity.md', 'Semantic preservation'),
('product density', 'references/product-value-integrity.md', 'Value density'),
('product aha', 'references/product-value-integrity.md', 'AHA / surprise'),
('product free ai', 'references/product-value-integrity.md', 'Free-AI replaceability'),
('product long', 'references/product-value-integrity.md', 'Long-book integrity'),
('site premium', 'references/site-studio-grade-standard.md', 'Studio-grade test'),
('site motion', 'references/site-studio-grade-standard.md', 'Motion architecture'),
('about', 'references/site-studio-grade-standard.md', '5 посетительских вопросов'),
('thanks', 'references/site-studio-grade-standard.md', 'Conversion completion states'),
('exec derived', 'references/executive-control-layer.md', 'Derived, not duplicated'),
('exec workspace', 'references/executive-control-layer.md', 'Owner Workspace evolution'),
('money', 'references/finance-capital.md', 'downside'),
('legal', 'references/legal-accounting-ip-ru.md', 'official legal sources'),
('ops', 'references/operations-delivery.md', 'capacity'),
('qa', 'references/qa-redteam-release.md', 'independent'),
('learning', 'references/learning-promotion-loop.md', 'Learning is evidence, not memory magic'),
('context memory', 'references/execution-memory.md', 'Context engineering / high-signal memory'),
('subagents', 'references/multi-agent-orchestration.md', 'Independent verifier role'),
('context helper', 'scripts/context_gap_resolver.py', 'ASK_OWNER_DIAGNOSTIC'),
('context retrieve', 'scripts/context_gap_resolver.py', 'RETRIEVE_SOURCE'),
('quick bank', 'references/quick-command-palette.md', '/рабочее-место'),
('r6 identity', 'SKILL.md', 'global-creative-product-intelligence-r9'),
('sales demand rule', 'SKILL.md', 'SALES DEMAND / SAFE AUTOPILOT'),
('raw footage rule', 'SKILL.md', 'RAW FOOTAGE EDITOR'),
('edit trend bank rule', 'SKILL.md', 'EDIT PATTERN / TREND BANK'),
('content mix rule', 'SKILL.md', 'CONTENT PERSONALITY MIX'),
('personal ai rule', 'SKILL.md', 'PERSONAL AI / FAMILY / SYSADMIN ADVISOR'),
('camera assumption', 'SKILL.md', 'CAMERA LEARNING ≠ FEAR ASSUMPTION'),
('client source map', 'references/sales-demand-generation-autopilot.md', 'Карта источников клиентов'),
('lead signals', 'references/sales-demand-generation-autopilot.md', 'Сигналы потенциального клиента'),
('sales automation ladder', 'references/sales-demand-generation-autopilot.md', 'Лестница автоматизации продаж'),
('sales legality', 'references/sales-demand-generation-autopilot.md', 'Законность, приватность и правила площадки'),
('funnel variants', 'references/sales-demand-generation-autopilot.md', '2–4 применимые архитектуры'),
('raw transcript', 'references/raw-footage-editing-trend-bank.md', 'Монтаж по транскрипту'),
('natural speech', 'references/raw-footage-editing-trend-bank.md', 'Правило естественности'),
('best take', 'references/raw-footage-editing-trend-bank.md', 'Выбор лучшего дубля'),
('technical correction', 'references/raw-footage-editing-trend-bank.md', 'Техническая коррекция'),
('edit mechanics bank', 'references/raw-footage-editing-trend-bank.md', 'Банк монтажных механик'),
('fresh refs', 'references/raw-footage-editing-trend-bank.md', 'Откуда брать свежие референсы'),
('trend card', 'references/raw-footage-editing-trend-bank.md', 'Trend card'),
('camera training', 'references/raw-footage-editing-trend-bank.md', 'Обучение Светланы съёмке'),
('content roles', 'references/content-personality-creator-mix.md', 'Контентные роли'),
('creator mode', 'references/content-personality-creator-mix.md', 'Creator mode / UGC-like'),
('personal radar', 'references/personal-ai-life-sysadmin-advisor.md', 'Личный AI Opportunity Radar'),
('children tutor', 'references/personal-ai-life-sysadmin-advisor.md', 'Обучение детей'),
('device architect', 'references/personal-ai-life-sysadmin-advisor.md', 'Системный администратор и архитектор устройств'),
]
errs=[]
for name,rel,phrase in checks:
    p=root/rel
    if not p.exists() or phrase.lower() not in p.read_text('utf-8',errors='ignore').lower(): errs.append(f'{name}: {rel} :: {phrase}')
if len(checks)!=125: errs.append(f'test itself must have 125 angles, has {len(checks)}')
if errs:
    print('НЕ ПРОЙДЕНО',len(errs),'ошибок /',len(checks),'ракурсов')
    [print('-',e) for e in errs]
    sys.exit(1)
print('ПРОВЕРКА ПРОЙДЕНА: 125/125 ракурсов')
